SET MODE Oracle;
CREATE SCHEMA IF NOT EXISTS GMICR;

-- Limpieza total de tablas previas
DROP TABLE IF EXISTS GMICR.TICR001_CONTRATO;
DROP TABLE IF EXISTS GMICR.TICR002_CLIENTE;
DROP TABLE IF EXISTS GMICR.TICR005_EXPEDIENTE;
DROP TABLE IF EXISTS GMICR.TICR11_EVENTOS;

-- 1. Tabla Principal: Añadimos todas las columnas que pide el MICRR174Impl
CREATE TABLE GMICR.TICR001_CONTRATO (
    CD_BANCO VARCHAR(10), 
    CD_OFICINA VARCHAR(10), 
    CD_CONTRAPARTIDA VARCHAR(10),
    CD_FOLIO_IUC VARCHAR(50), 
    CD_FOLIO VARCHAR(50), 
    CD_CONTRA_CLAN VARCHAR(50), 
    CD_SINDBILATERAL VARCHAR(50), 
    COLLECTIVE_LOAN_NUMBER_ID VARCHAR(50),
    CD_USUARIO_CAP VARCHAR(50), 
    TM_PETICION TIMESTAMP, 
    TM_MODIF TIMESTAMP,
    CD_FOLIOP VARCHAR(50), 
    CD_ESTADO VARCHAR(20), 
    TP_CONTRATO VARCHAR(20)
);

-- 2. Tabla de Clientes
CREATE TABLE GMICR.TICR002_CLIENTE (
    CD_CONTRA_CLAN VARCHAR(50),
    CD_PERSONA VARCHAR(50)
);

-- 3. Tabla de Expedientes
CREATE TABLE GMICR.TICR005_EXPEDIENTE (
    CD_FOLIOP VARCHAR(50),
    TP_SINDICATO VARCHAR(50),
    ST_ROL_BBVA VARCHAR(50),
    NB_FIN_SOSTENIBLE VARCHAR(50)
);

-- 4. Tabla de Eventos (Logs)
CREATE TABLE GMICR.TICR11_EVENTOS (
    CD_EVENTO VARCHAR(10),
    ST_EVENTO VARCHAR(10),
    TX_EVENTO VARCHAR(300),
    CD_IND_PROCESO VARCHAR(10)
);

-- ==========================================================
-- DATA DE PRUEBA: 3 REGISTROS (Asegurando que pasen el filtro del Reader)
-- El Reader busca: CD_ESTADO IN ('VIGENTE', 'ACTIVO') y TP_CONTRATO = 'DISPOSICION'
-- ==========================================================

-- REGISTRO 1
INSERT INTO GMICR.TICR001_CONTRATO (CD_BANCO, CD_OFICINA, CD_CONTRAPARTIDA, CD_FOLIO_IUC, CD_FOLIO, CD_CONTRA_CLAN, CD_SINDBILATERAL, COLLECTIVE_LOAN_NUMBER_ID, CD_USUARIO_CAP, CD_ESTADO, TP_CONTRATO, CD_FOLIOP, TM_PETICION, TM_MODIF) 
VALUES ('0012', '1234', 'CONT-001', 'IUC-101', 'FOL-101', 'CLAN-100', 'SIND-101', 'COLL-101', 'USER01', 'VIGENTE', 'DISPOSICION', 'FP-101', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO GMICR.TICR002_CLIENTE VALUES ('CLAN-100', 'PER-BBVA-001');
INSERT INTO GMICR.TICR005_EXPEDIENTE VALUES ('FP-101', 'SYNDICATED', 'AGENT', 'YES');

-- REGISTRO 2
INSERT INTO GMICR.TICR001_CONTRATO (CD_BANCO, CD_OFICINA, CD_CONTRAPARTIDA, CD_FOLIO_IUC, CD_FOLIO, CD_CONTRA_CLAN, CD_SINDBILATERAL, COLLECTIVE_LOAN_NUMBER_ID, CD_USUARIO_CAP, CD_ESTADO, TP_CONTRATO, CD_FOLIOP, TM_PETICION, TM_MODIF) 
VALUES ('0012', '5678', 'CONT-002', 'IUC-102', 'FOL-102', 'CLAN-200', 'SIND-102', 'COLL-102', 'USER02', 'ACTIVO', 'DISPOSICION', 'FP-102', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO GMICR.TICR002_CLIENTE VALUES ('CLAN-200', 'PER-BBVA-002');
INSERT INTO GMICR.TICR005_EXPEDIENTE VALUES ('FP-102', 'BILATERAL', 'PARTICIPANT', 'NO');

-- REGISTRO 3
INSERT INTO GMICR.TICR001_CONTRATO (CD_BANCO, CD_OFICINA, CD_CONTRAPARTIDA, CD_FOLIO_IUC, CD_FOLIO, CD_CONTRA_CLAN, CD_SINDBILATERAL, COLLECTIVE_LOAN_NUMBER_ID, CD_USUARIO_CAP, CD_ESTADO, TP_CONTRATO, CD_FOLIOP, TM_PETICION, TM_MODIF) 
VALUES ('0012', '9999', 'CONT-003', 'IUC-103', 'FOL-103', 'CLAN-300', 'SIND-103', 'COLL-103', 'USER03', 'VIGENTE', 'DISPOSICION', 'FP-103', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO GMICR.TICR002_CLIENTE VALUES ('CLAN-300', 'PER-BBVA-003');
INSERT INTO GMICR.TICR005_EXPEDIENTE VALUES ('FP-103', 'SYNDICATED', 'LENDER', 'YES');